<a href="https://colab.research.google.com/github/aryanp2107/PyTorch-Essentials/blob/main/PyTorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.empty(3)
print(x)

tensor([-3.3363e+32,  4.5189e-41, -3.3363e+32])


In [ ]:
y = torch.empty(2, 3, 3)
print(y)

tensor([[[4.4655e-07, 4.5190e-41, 1.2845e-18],
         [0.0000e+00, 2.7155e-21, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 1.2867e-18, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [ ]:
z = torch.rand(2, 2)
print(z)

tensor([[0.1740, 0.3244],
        [0.2765, 0.8435]])


In [ ]:
print(torch.ones(2, 2))

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(y.dtype)

torch.float32


In [ ]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x.size())

torch.Size([2, 2])


In [ ]:
xa = torch.tensor([2.4, 2.2])
print(xa)

tensor([2.4000, 2.2000])


In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.0134, 0.7504],
        [0.8886, 0.9305]])
tensor([[0.3229, 0.4140],
        [0.9282, 0.0636]])


In [ ]:
z = x + y
print(z)

tensor([[0.3364, 1.1644],
        [1.8167, 0.9941]])


In [ ]:
z = torch.add(x, y)
print(z)

tensor([[0.3364, 1.1644],
        [1.8167, 0.9941]])


In [ ]:
y.add_(x)
print(y)

tensor([[0.3364, 1.1644],
        [1.8167, 0.9941]])


In [ ]:
z = x - y
# or z = torch.sub(x, y)\
print(z)

tensor([[-0.3229, -0.4140],
        [-0.9282, -0.0636]])


In [ ]:
z = torch.mul(x, y)
print(z)

tensor([[0.0045, 0.8737],
        [1.6143, 0.9250]])


In [ ]:
z = torch.div(x, y)
print(z)

tensor([[0.0400, 0.6444],
        [0.4891, 0.9360]])


In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1900, 0.2101, 0.4634],
        [0.2705, 0.8788, 0.6531],
        [0.5783, 0.2427, 0.3041],
        [0.2604, 0.5597, 0.0086],
        [0.4438, 0.8340, 0.7513]])


In [ ]:
#Slicing
print(x)
print(x[:, 0])

tensor([[0.1900, 0.2101, 0.4634],
        [0.2705, 0.8788, 0.6531],
        [0.5783, 0.2427, 0.3041],
        [0.2604, 0.5597, 0.0086],
        [0.4438, 0.8340, 0.7513]])
tensor([0.1900, 0.2705, 0.5783, 0.2604, 0.4438])


In [ ]:
print(x[1, :])

tensor([0.2705, 0.8788, 0.6531])


In [ ]:
print(x[1, 1])

tensor(0.8788)


In [ ]:
print(x[1, 1].item())

0.8787717819213867


In [ ]:
#Reshaping a tensor
x = torch.rand(4, 4)
print(x)
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([[0.3025, 0.0777, 0.9707, 0.0212],
        [0.7261, 0.5563, 0.7072, 0.7788],
        [0.1326, 0.3712, 0.2006, 0.3231],
        [0.2290, 0.0888, 0.4425, 0.2051]])
tensor([[0.3025, 0.0777, 0.9707, 0.0212, 0.7261, 0.5563, 0.7072, 0.7788],
        [0.1326, 0.3712, 0.2006, 0.3231, 0.2290, 0.0888, 0.4425, 0.2051]])
torch.Size([2, 8])


In [ ]:
# Converting from numpy to torch tensors
import numpy as np

a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [ ]:
print(b)
#This will add to both of them coz they point to the same memory location

[2. 2. 2. 2. 2.]


In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    print(z)

In [ ]:
z

tensor([[0.0400, 0.6444],
        [0.4891, 0.9360]])

Gradient Calculation with Autograd

In [ ]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

tensor([2.2979, 1.1330, 0.5632], requires_grad=True)
tensor([4.2979, 3.1330, 2.5632], grad_fn=<AddBackward0>)


In [ ]:
z = y*y*2
print(z)

tensor([36.9443, 19.6312, 13.1395], grad_fn=<MulBackward0>)


In [ ]:
z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor(23.2384, grad_fn=<MeanBackward0>)
tensor([5.7306, 4.1773, 3.4175])


In [ ]:
x = torch.randn(3, requires_grad=False)
print(x)
#We must specify if we need parrarel computation of gradient descent

tensor([0.4083, 0.2883, 0.4989])


In [ ]:
x = torch.randn(3, requires_grad=True)

#x.requires_grad_(False)
#x.detach()
# with torch.no_grad()

x.requires_grad_(False)
print(x)

tensor([0.2644, 0.1310, 1.0282])


In [ ]:
y = x.detach()
y

tensor([0.2644, 0.1310, 1.0282])

In [ ]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(1):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(2):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()